### ISSUE TITLE
instrument Solute

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#103]
From #92:

> - [ ] Do we need an API for solutes? What do you want to be able to inspect about a solute?

2/6/20 design meeting decision: phetioID, nameProperty, pH

**Comment by pixelzoom** [comment]
I instrumented SoluteIO as requested, and tested in Studio and State Wrapper.

Inspecting the Solute instances shows none of the desired information.  E.g.:

<img width="443" alt="screenshot_101" src="https://user-images.githubusercontent.com/3046552/73989485-27d19e80-4903-11ea-858e-c01e0a7a4f4c.png">

Inspecting `soluteProperty` _does_ show the desired info:

<img width="759" alt="screenshot_102" src="https://user-images.githubusercontent.com/3046552/73989519-46379a00-4903-11ea-92cb-c96e85cbfe7a.png">

There was a long-ish discussion about this on the Slack phet-io channel.  This is apparently a PhET-iO deficiency, and @zepumph created https://github.com/phetsims/phet-io/issues/1616.  

So this is blocked until this is addressed generally in Studio.

**Comment by pixelzoom** [comment]
@samreid pointed out that `Solute` was `phetioState: false`.  Changing that to `true` shows the state information, see below. 

@arouinfar please test drive in master, inspect solutes under `phScale.global.model.solutes`.  If this looks sufficient, feel free to close.

<img width="639" alt="screenshot_135" src="https://user-images.githubusercontent.com/3046552/74885244-4fc4f700-5332-11ea-9f6d-6d28fac59450.png">

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom, closing.

**Comment by zepumph** [comment]
Note that we changes this implementation over in https://github.com/phetsims/phet-io/issues/1616 with https://github.com/phetsims/ph-scale/commit/c665cbaad44676769321b9e5e96963ecd0d3e49e. Because we no longer to require it to be phetioState to get studio info about the solutes. Anyone please feel free to reopen if  needed, but things are still the same. . .

This is what the same studio look now holds:

![image](https://user-images.githubusercontent.com/6856943/105431374-f0d2c680-5c01-11eb-8322-4c725ac9c024.png)

**Comment by pixelzoom** [comment]
I'll take your word for it.
