### ISSUE TITLE
Should dropper be movable?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#118]
During #117, @kathy-phet and I noticed that the dropper is movable. We don't see any pedagogical value in allowing users to move the dropper, and I couldn't find a reason for it in the design doc. Since the dropper didn't appear in the Java sim, the behavior isn't simply a holdover.

@pixelzoom @ariel-phet do you remember an explicit decision around making the dropper movable? How would you feel about removing the ability to move it?

**Comment by arouinfar** [comment]
Note that we would need to get rid of `view.dropperNode.dragHandler` if the dropper isn't movable. (Not sure if that would come for free or not.)

**Comment by ariel-phet** [comment]
I see no pedagogical reason, it is fairly constrained right now. My guess is people thought it was somewhat more playful. If you or @kathy-phet wants to remove that ability, seems fine by me.

**Comment by pixelzoom** [comment]
My recollection was that the dropper was made horizontally draggable to make the sim more interactive and fun.    

If you want its location to be fixed, its more involved than simply removing its DragListener.  The model will also need to be changed.  Dropper currently extends Movable, which is where it gets its `positionProperty`.  

If you the fixed position to be something other than the current default, then examine `phScale.macroScreen.model.dropper.positionProperty` in Studio and tell me what position you'd like.

**Comment by kathy-phet** [comment]
Then perhaps we just leave it as is. It's not hurting anything. I will note it is not currently possible to make it unmoveable/unpickable without also making the add liquid button unpickable/not working. Let's discuss at an upcoming mini-design meeting.

**Comment by pixelzoom** [comment]
Also note that the dropper is movable in Beer's Law Lab and Concentration. 

Perhaps there should be a general solution for disabling a Node's drag listener?

**Comment by arouinfar** [comment]
> Perhaps there should be a general solution for disabling a Node's drag listener?

@kathy-phet and I think this is likely to come up in other sims like Bending Light. A client may want to fix the position of the LaserNode, but leave the button on it interactive. We're going to mark this issue for further discussion at PhET-iO meeting.

**Comment by pixelzoom** [comment]
Thinking out loud... How about adding `enabledProperty` to all listeners (`SimpleDragHandler`, `DragListener`, `PressListener`,...)  Then you would disable interactivity by setting the listener's `enabledProperty:false`, rather than changing `pickableProperty:false` on the Node that the listener is attached to.

**Comment by pixelzoom** [comment]
`pickableProperty` (like `visibleProperty` and `opacityProperty`) applies to a Node and all of its children.  So it makes sense that setting `pickableProperty: false` for the `dropperNode` would disable interactivity for all parts of dropperNode, including its push button. And  I don't think we want to change that behavior. 

How about adding the ability to disable listeners? We could add `enabledProperty` to all listeners (`SimpleDragHandler`, `DragListener`, `PressListener`,...)  Then you would disable dragging of `dropperNode` by setting `dropperNode.dragHandler.enabledProperty: false`, rather than setting `dropperNode.pickableProperty:false`. Or if you wanted to to disable interactivity of the dropper's button, you'd set `dropperNode.button.pressListener.enabledProperty: false`.

**Comment by pixelzoom** [comment]
I've moved the general discussion about how to disable listeners to https://github.com/phetsims/ph-scale/issues/133.

**Comment by pixelzoom** [comment]
I've moved the general discussion about how to disable listeners to https://github.com/phetsims/ph-scale/issues/133.

So our remaining decisions here are:

(1) Whether the dropper should be draggable. If not, then (2) is moot.

(2) Whether what we come up with in https://github.com/phetsims/scenery/issues/1041 should be applied here to allow the client to disable dragging of the dropper.

**Comment by pixelzoom** [comment]
3/5/20 design meeting:

* keep the dropper movable
* we don't want to change the tandem hierarchy for dropperNode
* address disabling input listeners in phetsims/scenery#1041 

Closing.
