### ISSUE TITLE
Creating solution with specific pH

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#119]
In #117 @kathy-phet and I thought about how a client might set up a solution with a specific pH. It is hard to set precise values for the solute and solvent amounts using the sim UI, and we can imagine that a client may want more precise control over this (or could potentially want to ask students to create a solution with a specific pH in a wrapper). 

We think the user could do this by specifying `model.solution.waterVolumeProperty` and `model.solution.soluteVolumeProperty` but these values are read only. We were not sure if simply making these properties `phetioReadOnly: false` would be sufficient to address these needs.

@pixelzoom how would you address this?

**Comment by pixelzoom** [comment]
The problem with making `model.solution.waterVolumeProperty` and `model.solution.soluteVolumeProperty` `phetioReadOnly: false` is that their range is dynamic. Together `waterVolumeProperty + soluteVolumeProperty` must be <= 1.2L, which is the capacity of the beaker. 

If we simply make them each Property have a range of [0,1.2] L, then that makes it possible to overflow the beaker.  Example:

By default, we start with 0.5L of solute:

<img width="639" alt="screenshot_151" src="https://user-images.githubusercontent.com/3046552/75402836-2a506400-58c3-11ea-8d2e-86197caa2aa8.png">

I use the slider in Studio to increase `model.solution.soluteVolumeProperty` to 1.2L:

<img width="640" alt="screenshot_152" src="https://user-images.githubusercontent.com/3046552/75402980-861aed00-58c3-11ea-8298-b125e2de0be3.png">

The beaker is now full.  But I can still use the slider in Studio to increase `model.solution.waterVolumeProperty`:

<img width="640" alt="screenshot_153" src="https://user-images.githubusercontent.com/3046552/75403007-9b901700-58c3-11ea-87b2-f139c964c58b.png">

This is obviously very wrong. The model was not designed for this. The model knows how to limit the solution volume to 1.2L, but these Properties do not.  

A dynamic range feature was recently added to `NumberProperty`.  So if you want this feature, that's the way to add it.  It will be a significant piece of work, and I don't know what other issues I'll run into.    

The other option would be to let the beaker overflow, as in the above example. It doesn't seem to break the sim in any obvious way.  But again, the model wasn't designed for this, so I don't recommend it.

Let me know how you want to proceed.

**Comment by pixelzoom** [comment]
Note that this also does not address setting a specific pH in the _My Solutions_ screen.  That would involve making `phScale.mySolutionsScreen.model.solution.pHProperty` have `phetioReadOnly: false` -- which is impossible because it's a DerivedProperty.    The way to set a specific pH in the _My Solutions_ screen is to use the pH Meter spinners.

**Comment by kathy-phet** [comment]
I suggest we do a mini-PhET-iO meeting around pHscale - perhaps at next week's design meeting - and discuss there. Thanks for explaining the options.

**Comment by arouinfar** [comment]
Thanks for the explanation @pixelzoom. I will be requesting design meeting time for ph-scale, so we can continue the discussion then.

Extra notes from the design review of the My Solution screen:

Theoretically, it seems like a client should be able to use `mySolutionsScreen.model.solution.pHProperty` to set the pH of a solution through an API. However, the property is read only. What implications would there be for setting this property to `phetioReadOnly: false`?

**Comment by pixelzoom** [comment]
It's not possible to make `mySolutionsScreen.model.solution.pHProperty` `phetioReadOnly: false`.  It's currently a DerivedProperty, and those cannot be set directly -- either programmatically or otherwise -- because they are derived from other Property values.  

It is a DerivedProperty because that is the case in the first 2 screens. And the _My Solutions_ screen uses the same model as the other screens, in this manner: The volume of water in the beaker is always zero.  Each time the pH is changed via the spinners on the meter, a solute with that pH is created, and 1/2L of that solute is put in the beaker.  `pHProperty` is then derived from  the solute's pH, soluteVolume, and waterVolume. 

If you want `mySolutionsScreen.model.solution.pHProperty` to be settable via PhET-iO, we will need to implement an entirely new model for this screen.

**Comment by pixelzoom** [comment]
If you really want to support setting a specific pH, here's my recommendation:

For _Micro_ and _Macro_ screens, investigate using the dynamic range feature of `NumberProperty` to set ranges for `waterVolumeProperty` and `soluteVolumeProperty`, such that their total is always <= 1.2L.  Then make both of those Properties `phetioReadOnly: false` so that they can be edited in Studio.  Estimate: 2-4 hours.

For _My Solution_ screen, investigate creating an entirely new model, and/or a Solute with mutable pH.  If we make the above changes to the other screens, this is likely to be required, not an optional additional task. Estimate: 6-8 hours.

**Comment by pixelzoom** [comment]
3/5/20 design meeting:

* Investigate dynamic range for waterVolumeProperty and soluteVolumeProperty. If it doesn't work out, still do `phetioReadOnly: false`, and allow them to exceed 1.2L as long as it doesn't crash the sim.  Add phetioDocumentation to those Properties that it's the clients' responsibility not to exceed 1.2L.

* No Studio slider -- `phetioStudioControl: false` for waterVolumeProperty and soluteVolumeProperty

* For _My Solution_, instrument `spinnerProperty` in PHMeterNode, make sure there isn't a problem with `reentrant: true`.   Document in `model.pHProperty` to use `spinner.pHProperty` to set.

**Comment by pixelzoom** [comment]
In the above commit, I made some rather major changes to make pHProperty directly settable in My Solution screen.

Still to do:

- [ ] Create `class MicroSolution extends Solution`, add in the Properties from `Graph` and `MoleculesNode`.
- [ ] Remove `getMolecules*` methods from `Solution`.
- [ ] Add dynamic ranges to `Solution` `waterProperty` and `soluteProperty`.
- [ ] Investigate getting rid of the cleverness in `MySolutionModel`

**Comment by pixelzoom** [comment]
Major changes where required to provide the ability to set a specific pH.  

Summary:

* _Macro_ and _Micro_ screens now support setting `model.solution.soluteVolumeProperty` and `model.solution.waterVolumeProperty` via the PhET-iO API -- they are `phetioReadOnly: false`.

* I investigated setting dynamic ranges for `soluteVolumeProperty` and `waterVolumeProperty` But it turned into a big mess, so....

* If the client sets `soluteVolumeProperty` or  `waterVolumeProperty` via the PhET-iO API, it is their responsibility to ensure that the total volume is <= 1.2L. This is noted in the `phetioDocumentation` for those Properties.  If the total volume exceeds 1.2L, the sim will not break, but the beaker will appear to overflow. 

* There are no Studio controls (sliders) for `soluteVolumeProperty` and `waterVolumeProperty`, again because their ranges are interdependent and dynamic. 

* _My Solution_ screen has a new model that supports setting pH directly via `model.solution.pHProperty`.  It's `totalVolumeProperty` can be set via Studio, and its value must be > 0, so its range is currently [0.01,1.2] L -- this can be changed easily if desired.

* Properties formerly in `model.graph` and `view.moleculeCountNode` are now found under `model.solution`.

@arouinfar please verify in master.

**Comment by arouinfar** [comment]
Reviewed with @kathy-phet and it looks good in master.
