### ISSUE TITLE
Can GraphIndicatorNode be snappy when dragged?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#134]
During #117, @kathy-phet commented that it is hard to set specific values when dragging the GraphIndicatorNodes on the My Solution Screen. We were wondering if it would be possible to snap the values to the nearest 1.0 when dragging the GraphIndicatorNode. For example, when dragging the H3O+ GraphIndicatorNode up from the default position, the values would snap to:

1.0E-7
2.0E-7
3.0E-7
...
1.0E-6
2.0E-6
etc.

The OH- GraphIndicatorNode would go to its calculated position, which could still correspond to a messier value. Likewise, the GraphIndicatorNodes won't necessarily have nice values when the pH is changed using the control on the pH meter.

Tagging for discussion at design meeting.

**Comment by pixelzoom** [comment]
3/5/20 design meeting:

I'll evaluate.  If it's not easy, report back.  Otherwise do it.

**Comment by pixelzoom** [comment]
Reporting back... A "snap to" drag handler is not going to be easy.  GraphIndicatorNode has no knowledge of what the exponent is, that's handled by scenery-phet.ScientificNotationNode.   So there's currently no way to easily determine the "value to the nearest 1.0".   

I'm also skeptical that this will be usable, because integer mantissas are only a few pixels apart, and they get closer together as the mantissa gets closer to 9.0 (because the scale is log).  So I think it's going to feel odd _and_ be marginally usable.

If setting the indicator to specific values is important, then adding a spinner (or arrow buttons) would result in a more usable UI.  Like NumberControl, you'd drag the indicator to get close, then use the buttons to get precise.

@arouinfar how do you want me to proceed?

**Comment by arouinfar** [comment]
@pixelzoom I am perfectly happy to proceed without the snappy behavior and close this issue. I can't remember if @kathy-phet commented on this when you mentioned in your status report, so I'll assign her for a final sign off.

**Comment by kathy-phet** [comment]
Amy and I reviewed this together, and we are OK with leaving it as is. Thanks for taking a look. Closing.
