### ISSUE TITLE
Concentration/Quantity labels no longer centered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#149]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/487. Not in the published version.
The concentration/quantity toggle and text are now on the right side of their box rather than centered. This is seen when strings are shorter than normal (i.e. stringTest=X).

**Visuals**
Now:
![now](https://user-images.githubusercontent.com/41024075/77483849-c439fc80-6dee-11ea-9ebf-5c88575b40d3.png)
Published:
![published](https://user-images.githubusercontent.com/41024075/77483879-cef49180-6dee-11ea-87d6-9e2bfd32be38.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: X
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.15/phet/ph-scale_all_phet.html?stringTest=X
Version: 1.4.0-dev.15 2020-03-23 21:08:00 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Fixed in the above commit.  I also adjusted the margin and position the expand/collapse button where it should be -- in the upper-right corner.    See screenshots below. 

@KatieWoe please verify in master.

No stringTest:

<img width="365" alt="screenshot_205" src="https://user-images.githubusercontent.com/3046552/77509088-c07b9980-6e31-11ea-81db-43d900727121.png">

`?stringTest=long`
<img width="367" alt="screenshot_206" src="https://user-images.githubusercontent.com/3046552/77509102-c6717a80-6e31-11ea-94ac-57c8a75bee31.png">

`?stringTest=X`
<img width="373" alt="screenshot_207" src="https://user-images.githubusercontent.com/3046552/77509122-ccfff200-6e31-11ea-9f50-8ebbaa426ea1.png">

**Comment by KatieWoe** [comment]
Not sure if it's https://github.com/phetsims/ph-scale/issues/150 or this, but rtl now throws an error and doesn't load:
![newrtlissue](https://user-images.githubusercontent.com/41024075/77551080-8503be00-6e77-11ea-9636-a9d3c4b1e991.png)
It does seem to load in the built version.

**Comment by KatieWoe** [comment]
Otherwise looks ok on master

**Comment by pixelzoom** [comment]
The stringTest=rtl is not related to this issue. Moved to #151.

Closing.
