### ISSUE TITLE
Solutions diluted enough to be neutral may not show it properly

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#153]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/487. Not in published sim.
When your solution is neutral because you used the water dropper or only the faucet, there is a small dialog that says neutral and the pH reader has a black outline around it. If, however, you dilute a non-neutral solution enough that it becomes neutral, this doesn't happen in the dev version. The pH reader says 7.00, but the black outline isn't there and the neutral dialog isn't there either. In the published version both neutral indicators are there.
**Steps to reproduce**
1. Choose a solution (Coffee was used in the example)
2. Put the pH meter in near the bottom
3. Fill rest of bucket with water
4. Drain partially, leaving solution in the bottom
5. Repeat until pH reaches 7

**Visuals**
![shouldneutral](https://user-images.githubusercontent.com/41024075/77577954-57317000-6e9d-11ea-9d7e-03b14909b922.png)
vs
![notproperneutral](https://user-images.githubusercontent.com/41024075/77577971-5ac4f700-6e9d-11ea-9a5e-97b984958022.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.15/phet/ph-scale_all_phet.html
Version: 1.4.0-dev.15 2020-03-23 21:08:00 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Looks like a consequence of #143. If recreate this in studio, you'll see that the value of the pH is not exactly 7.00, which is probably why the neutral indicator doesn't appear.

@pixelzoom can the neutral indicator appear if the pH rounds to 7.00?

**Comment by pixelzoom** [comment]
Specifically due to this change in #143:

> - [x]  In the _Macro_ and _Micro_ screens, we do not want pHProperty's value to be round to a multiple of 0.01 increments. We want the full-resolution value.

Should be doable, I'll have to handle rounding in the view components.  Hopefully the pH meter and "Neutral" indicator are the only cases.

**Comment by pixelzoom** [comment]
Fixed in master.  @KatieWoe please review, close if OK.

**Comment by KatieWoe** [comment]
Looks good from what I can see on master

**Comment by KatieWoe** [comment]
I noticed that the rounding to neutral can occur in the pH before it happens in H3O and OH concentration indicators. @pixelzoom is this acceptable? If so, please close again.
![pH Scale screenshot](https://user-images.githubusercontent.com/41024075/77959952-b3790300-7294-11ea-9f5c-9ba86032df01.png)
![pH Scale screenshot (1)](https://user-images.githubusercontent.com/41024075/77959958-b70c8a00-7294-11ea-9a5e-3c3ff2535723.png)

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. It should occur at the same time in all view components, so I'll address this is the graph indicators too.

**Comment by pixelzoom** [comment]
Sorry, my previous comment was incorrect.  The graph indicators are much more precise than the pH meter.  So if you have a highly-diluted solution, the pH meter is going to show it's pH as 7.00 for many values of the graph indicators.  There's no way that those indicators can go "neutral" at the same time as the pH meter.  So you'll see the pH meter read "7.00" first, and as you continue to add water you will eventually see the H<sub>3</sub>O<sup>+</sup> and OH<sup>-</sup> concentrations go to 1 x 10<sup>-7</sup>.

And after #119, I don't think we want try to play games with the model, like setting the pH to exactly 7 when it gets "close to 7". 

@arouinfar do you agree?

**Comment by arouinfar** [comment]
> After the major changes in #119, I don't think we want try to play games with the model, like setting the pH to exactly 7 when it gets "close to 7".
>
>@arouinfar do you agree?

I agree. Let's not go there.

@kathy-phet due to the rounding changes we requested in #143, the "Neutral" indicator was not showing up in the beaker because the pH was never exactly 7 (except at startup/selecting water). @pixelzoom was able to change the behavior so that "Neutral" appears in the beaker when the pH rounds to 7.00, and it's behaving as expected. However, a side effect of this change is the the concentrations of H3O+ and OH- will reveal that the concentration isn't exactly 7 (see screenshots in https://github.com/phetsims/ph-scale/issues/153#issuecomment-606238824). Is this acceptable behavior? If not, then we should reconsider displaying "Neutral" when the pH rounds to 7.00.

**Comment by pixelzoom** [comment]
@arouinfar said:
> ... If not, we should reconsider displaying "Neutral" when the pH rounds to 7.00.

Reminder that the "Neutral Indicator" only appears in the _Macro_ screen. So it's not an issue in either of the screens that have graph indicators.

**Comment by arouinfar** [comment]
> Reminder that the "Neutral Indicator" only appears in the Macro screen. So it's not an issue in either of the screens that have graph indicators.

Ah, thanks for that @pixelzoom. In that case, I think it's perfectly acceptable for the pH meter to read 7.00 even if the graph indicators reveal that the pH is not exactly 7. The published sim behaves this way, and it is a natural consequence of rounding (which could lead to conversations about precision).

My concern was that users would be seeing the "Neutral" indicator at the same time as the graph revealed that the solution was not actually neutral. Since that'll never happen, I'm happy to close.
