### ISSUE TITLE
Pointer Area inconsistency for expand/collapse and toggle switch

### ISSUE THREAD

**Issue by stemilymill** [phetsims/ph-scale#224]
**Test device**
Dell laptop

**Operating System**
Win10

**Browser**
Chrome 91.0.4472.124

**Problem description**
For https://github.com/phetsims/qa/issues/669
Expand/collapse hitbox does not match what is shown in ?showPointerAreas, and actual hitbox does not match in pH and graph accordions
note: one of the query pointer area mismatches occurs in published version, but not the difference between the two accordions
The actual clickable area for the toggle switches makes sense, because it covers the area of the text labeling the switch. If the actual hitbox matched the apparent pointer area between pH and the graph accordion expand/collapse button, I would not have noticed this.

**Steps to reproduce**
Add query parameter showPointerAreas
Go to Micro or My Solution screen
Click anywhere in the title area of the pH accordion panel
Click around the graph area

**Visuals**
![pointer areas expandcollapse not match](https://user-images.githubusercontent.com/85511101/125707775-050378c3-8b9c-4bf4-82c0-9c180386ca86.gif)

![pointer areas accordion hitbox not match](https://user-images.githubusercontent.com/85511101/125709762-4ab06a63-14b6-445c-b45d-0eb9e852f034.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.5.0-rc.1/phet/ph-scale_all_phet.html
Version: 1.5.0-rc.1 2021-07-13 18:33:46 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
Thanks for report @stemilymill.  But this is not a problem, it's a feature :). 

Two things... 

(1) Clicking on labels is an alternative way of toggling AB switches and accordion boxes -- the 2 types of UI components that you've demonstrated here.  This is handled in common code, not specific to this sim, so expect to see this behavior in other sim.

(2) The labels do have default pointer areas, but you can't see them because scenery only displays pointer areas if you override the default.  Yes, this has been an ongoing source of confusion - it's been suggested to change this, but it hasn't happened.

So... Does that make sense? If so, please close.

**Comment by stemilymill** [comment]
@pixelzoom yes, all makes sense, the main part I thought might actually be a problem is that in the published version, to toggle the pH accordion box you have to actually click the +/- square button,  but in this RC version it is not limited to that area. Thanks for explaining it to me!

**Comment by pixelzoom** [comment]
The published version is quite old, and did not use AccordionBox.
