### ISSUE TITLE
Add showRatio query parameter to phet-io-guide

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#229]
Related to https://github.com/phetsims/qa/issues/677

Discovered in #228 when looking at the public query parameters in this sim. I was unaware of `showRatio`, but it should be included in  [phet-io-guide.md ](https://github.com/phetsims/phet-io-client-guides/blob/master/ph-scale/phet-io-guide.md) which documents all public-facing query parameters.

**Comment by arouinfar** [comment]
Done in the above commit. Ready for cherry-picking @pixelzoom.

**Comment by arouinfar** [comment]
Note that this query parameter is only relevant to ph-scale. No changes are necessary for ph-scale-basics.

**Comment by pixelzoom** [comment]
Patched for ph-scale 1.5:

```
% cd perennial
% grunt checkout-target --repo=ph-scale --target=1.5
% cd phet-io-client-guides
% git checkout -b ph-scale-1.5
% git cherry-pick 77cb323f0655d6f187152cddde35e21e5ebc11b2
% cd ph-scale
% grunt --brands=phet-io
// test
%  cd  phet-io-client-guides
% git push origin ph-scale-1.5
% cd ph-scale
% cp build/phet-io/dependencies.json .
% git add dependencies.json
% git commit -m "patch 1.5 branch for https://github.com/phetsims/ph-scale/issues/229"
% git push origin 1.5
```

Not necessary to patch for ph-scale-basics 1.5.

Ready for verification in next RC.

**Comment by pixelzoom** [comment]
To test in 1.5.0-rc.3:

1. Go to https://phet-dev.colorado.edu/html/ph-scale/1.5.0-rc.3/phet-io/
2. Click on "PhET-iO Guide" link
3. Verify that `showRatio` appears in the table for "Simulation-specific Query Parameters".

**Comment by KatieWoe** [comment]
Looks good in rc 3. I will note that the ratio can be hard to see near the extremes of ph

**Comment by pixelzoom** [comment]
@Katie do you mean the numbers are difficult to see, because the large number of molecules results in (effectively) a blue or red background?  See screenshots below.  

If so, that's a problem with the feature, not the query parameter or the PhET-iO Guide, and let's open a new issue.  This was originally a developer-only parameter.  When it was promoted to public-facing, we should have considered putting the numbers on a transparent white background.

<img width="507" alt="screenshot_1091" src="https://user-images.githubusercontent.com/3046552/127064569-c9d09c7f-cb38-48a3-96b3-b92245b6d1ea.png">

<img width="549" alt="screenshot_1092" src="https://user-images.githubusercontent.com/3046552/127064578-0137dc89-06b5-40ac-acd8-b964d8e06d4b.png">

**Comment by KatieWoe** [comment]
Yes, that is what I meant.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe, good point. I think this points to an error in making `showRatio` a public query parameter, see https://github.com/phetsims/ph-scale/issues/231.  And if that's the case, the commits here will need to be reverted.

**Comment by pixelzoom** [comment]
In #231, we decide that `showRatio` should be private.  So in the above commits, I removed `showRatio` from the PhET-iO Guide, in master and 1.5 branches.

Ready for verification in the next RC.  Steps to verify:

1. Go to https://phet-dev.colorado.edu/html/ph-scale/1.5.0-rc.4/phet-io/
2. Click on "PhET-iO Guide" link
3. Verify that `showRatio` DOES NOT appear in the table for "Simulation-specific Query Parameters".

**Comment by KatieWoe** [comment]
This has been don in rc4. Leaving open in case the team wants to do this after publication

**Comment by pixelzoom** [comment]
There's nothing else to be done here after publication, so I'll go ahead and close this.
