### ISSUE TITLE
Add support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#239]
... similar to what was done in https://github.com/phetsims/natural-selection/issues/319.

This also includes ph-scale-basics.

**Comment by pixelzoom** [comment]
Code specific to ph-scale-basics was completed in the above commit.

**Comment by pixelzoom** [comment]
Next on my list, so raising priority.

**Comment by pixelzoom** [comment]
Before doing this work, I published [1.6.0-dev.3](https://phet-dev.colorado.edu/html/ph-scale/1.6.0-dev.3) for `brands=phet,phet-io` as a baseline.

**Comment by pixelzoom** [comment]
In the above commits, I did the low-hanging fruit -- the StringProperties that are passed directly to a Text/RichText constructor.

I can already tell that this sim is going to have significant layout problems.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

**Comment by arouinfar** [comment]
@pixelzoom overall things look good in ph-scale. I didn't review the links to the StringProperties in the view components, since it sounds like that work is still outstanding. Let me know if you need any guidance before you begin. 

I found a few issues with dynamic layout:

1.  `pHStringProperty` - the text does not remain centered and escapes the bounds of the pH Meter.
     <img width="154" alt="image" src="https://user-images.githubusercontent.com/8419308/189437763-12bf300b-919e-4cff-8f66-2efa2fbd1438.png">
2.  `phScale.microScreen.view.beakerControlPanel.separator` does not change in size when the panel expands to accommodate long strings. Not sure if this is something that can be handled within the scope of dynamic layout, but wanted to point it out in case this behavior is unexpected or can be corrected. (Feel free to veto if overly complicated.)
     <img width="239" alt="image" src="https://user-images.githubusercontent.com/8419308/189440604-659e2e8c-6482-4f0c-a0d6-7401811b3c3a.png">

In ph-scale-basics, I'm seeing every single ph-scale string. Since there isn't a way to re-add the additional screens in Basics, these strings seem completely irrelevant. For example, many of these StringProperties relate to later screens.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/8419308/189439106-95672118-ac01-469d-ab4b-c33b066a2d89.png">

I wasn't sure how this was being handled in rosetta, so I compared to the Translation Utility. The strings specific to pH Scale (e.g. `linearStringProperty` or `moleculeCountStringProperty`) do not appear.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/8419308/189439293-f72a3575-a7ac-4dac-9457-bbc0fe758e56.png">

**Comment by pixelzoom** [comment]
1. and 2. above are certainly things that can be addressed. Thanks for identifying.

> In ph-scale-basics, I'm seeing every single ph-scale string.  ...

This is a general problem, not specific to ph-scale-basicis.  A sim's PhET-iO API currently includes every string Property, from every dependency repo, regardless of whether those strings are using in the sim.  Tracking in https://github.com/phetsims/phet-io/issues/1877.

**Comment by pixelzoom** [comment]
I've created separate issues for each things that @arouinfar reported in https://github.com/phetsims/ph-scale/issues/239#issuecomment-1242464933. Closing.
