### ISSUE TITLE
Add links to `stringProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#251]
Related to #241 

@pixelzoom there are a few places in the tree that could use a link back to the corresponding `stringProperty`

- [ ] `*.view.graphNode.graphControlPanel.graphUnitsSwitch.concentrationText` - link to both `concentrationStringProperty` and `molesPerLiterStringProperty`)
- [ ] `*.view.graphNode.graphControlPanel.graphUnitsSwitch.quantityText` - link to both `quantityStringProperty` and `molesStringProperty`
- [ ] `*.view.beakerControlPanel.moleculeCountCheckbox`
- [ ] `*.view.beakerControlPanel.ratioCheckbox` - just a link to `ratioStringProperty` since the H3O+/OH- portion isn't translatable/instrumented

I'm a bit on the fence when it comes to the Ratio checkbox, but it seems a little strange to have a linked `stringProperty` for one checkbox, but not the other.

**Comment by pixelzoom** [comment]
> - [ ] `*.view.graphNode.graphControlPanel.graphUnitsSwitch.concentrationText` - link to both `concentrationStringProperty` and `molesPerLiterStringProperty`)
> - [ ] `*.view.graphNode.graphControlPanel.graphUnitsSwitch.quantityText` - link to both `quantityStringProperty` and `molesStringProperty`
...
> - [ ] `*.view.beakerControlPanel.ratioCheckbox` - just a link to `ratioStringProperty` since the H3O+/OH- portion isn't translatable/instrumented

Because these are DerivedProperties, they are not links. It's a matter of instrumenting the DerivedProperties.  So the Studio tree for `graphUnitsSwitch` looks like:

<img width="379" alt="screenshot_1921" src="https://user-images.githubusercontent.com/3046552/194390547-2f108c77-f79b-4514-9b41-a57bfad271db.png">

And `beakerControlPanel.ratioCheckbox` looks like this:

<img width="393" alt="screenshot_1922" src="https://user-images.githubusercontent.com/3046552/194392573-6c45cb29-a7ca-44f9-8952-b6027c35e8d3.png">

> - [ ] `*.view.beakerControlPanel.moleculeCountCheckbox`

This one is indeed a linked element. It was appropriate to instrument for the Text element and the StringProperty. Here's the Studio tree:

Back to @arouinfar for review.
<img width="358" alt="screenshot_1923" src="https://user-images.githubusercontent.com/3046552/194392895-f29302a3-16e0-449b-a111-548644a60286.png">

**Comment by arouinfar** [comment]
> Because these are DerivedProperties, they are not links. It's a matter of instrumenting the DerivedProperties.

Thanks for the clarification @pixelzoom. Everything looks good in master, closing.
