### ISSUE TITLE
Incorrect terminology used ("molecule" vs "ion")

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ph-scale#258]
For https://github.com/phetsims/qa/issues/866
In the Micro and My Solution screens, the word "molecule" in the Molecule Count checkbox isn't the correct term. When checked, it shows the amounts of hydronium ion, hydroxide ion, and water molecules. Ions are not molecules, because molecules have no charge. Other options to consider are "particle" or "species."

From @arouinfar on Slack:
>You’re definitely right about the terminology. I tried looking for a paper trail on the feature on GitHub and the design doc, and didn’t find anything helpful. If it was just the name on the checkbox, I would change it in a heartbeat. Unfortunately, “molecule” appears in all sorts of places throughout the PhET-iO tree so it’s a somewhat major change. Can you log an issue for it? Even if we decide not to move forward, we should have a documented discussion and update the Teacher Tips.

**Comment by pixelzoom** [comment]
Here's an inventory of would need to change. Back to @arouinfar to advise on next steps.

### Strings

This is the most problematic part of the change. Currently we have this translated string:

```json
  "moleculeCount": {
    "value": "Molecule Count"
  },
```

... which is used to label this checkbox, which controls visibility of the counts shown above it:

<img width="276" alt="screenshot_2071" src="https://user-images.githubusercontent.com/3046552/208162259-4c20de9d-006b-4d9d-a1b0-ba7204d25ff2.png">

Since we're showing counts for _ions and a molecule_ (H<sub>2</sub>O), how do we label this checkbox?

If we introduce a new string, we'll need to notify translators after publication.

### Code:

Code is not visible to the user, but should be changed for maintainability. This will take ~20 minutes:

Searching for "molecules" (not case-sensitive):
* 61 occurences of in code constructs (variable names, method names, ...)
* 28 occurrence in code comments

### PhET-iO

This will change the API, and require migration rules. This will take ~30 minutes + PhET-iO team help:
* 4 tandem names to change in code, which will change the phetioIDs of 8 elements
* 2 phetioDocumentation to change in code, which will change the documentation for 4 elements

The new migration rules would look something like:

```
new TandemFragmentRenamed( 'numberOfH3OMoleculesProperty', 'numberOfHydroniumIonsProperty' );
new TandemFragmentRenamed( 'numberOfOHMoleculesProperty', 'numberOfHydroxideIonsProperty' );
```

**Comment by samreid** [comment]
> Ions are not molecules, because molecules have no charge.

According to Wikipedia:

> An ion (/ˈaɪ.ɒn, -ən/)[1] is an atom or molecule with a net electrical charge.

So perhaps it is OK to call ions molecules?

**Comment by Nancy-Salpepi** [comment]
When an atom gains/loses electrons and thus takes on charge, it is no longer called an atom. It is called an ion. The same goes for molecules.

**Comment by pixelzoom** [comment]
Lots of conflicting info out there...

Oxford dictionary:
> Ion: an atom or molecule with a net electric charge due to the loss or gain of one or more electrons

But then https://edu.rsc.org/cpd/atoms-molecules-and-ions/3010574.article:
> Students should understand that:
> * Particles can be atoms, molecules or ions.
> * Atoms are single neutral particles.
> * Molecules are neutral particles made of two or more atoms bonded together.
> * An ion is a positively or negatively charged particle.

Should we ask a chemist?  Or ChatGTP? :)

**Comment by pixelzoom** [comment]
> * Particles can be **atoms**, **molecules** or **ions**.

So maybe change "Molecule Count" to "Particle Counts"?

**Comment by Nancy-Salpepi** [comment]
I taught chemistry for 18 years. I also asked my friend who is a chemistry teacher and has a chemistry degree. Molecule is definitely not the correct term here. 
Yes--particle would be better in my/her opinion.

**Comment by samreid** [comment]
ChatGPT says:

> An ion is an atom or group of atoms that has a net electric charge due to the loss or gain of one or more electrons. Ions can be either positive or negative, depending on the number of electrons they have compared to the number of protons in the nucleus. Atoms can become ions by either losing or gaining electrons, so an ion is still considered to be an atom. However, the term "atom" usually refers to a neutral atom, which has the same number of protons and electrons, while the term "ion" specifically refers to an atom or group of atoms that has a net electric charge.

**Comment by pixelzoom** [comment]
So what I'm hearing is that atoms and molecules are inherently neutral particles. And when they become charged, its no longer appropriate to call them atoms and molecules, and they should be referred to as ions.  So what we have is 2 icons (H3O+ and OH-) and 1 molecule (H2O).   And since "Particles can be atoms, molecules or ions", it would be appropriate to refer to H3O+, OH-, and H2O together as "particles", and label the checkbox as "Particle Counts".

**Comment by pixelzoom** [comment]
Discussed with @arouinfar.  Here's what we're going to change:

new string:

```
  "particleCounts": {
    "value": "Particle Counts"
  },
```

tandem renames, for consistency with 

numberOfH2OMoleculesProperty -> particleCountH2OProperty
numberOfH3OMoleculesProperty ->particleCountH3OProperty
numberOfOHMoleculesProperty -> particleCountOHProperty
moleculeCountCheckbox -> particleCountsCheckbox
moleculeCountVisibleProperty -> particleCountsVisibleProperty
moleculeCountNode -> particleCountsNode
moleculeCountStringProperty -> particleCountsStringProperty (probably no migration rule, since this is new in 1.6)

**Comment by pixelzoom** [comment]
Worked with @samreid and @zepumph, and here are the migration rules that are needed for this issue:

```
// Change terminology from 'Molecule Count' to 'Particle Counts', https://github.com/phetsims/ph-scale/issues/258
new TandemFragmentRenamed( 'numberOfH2OMoleculesProperty', 'particleCountH2OProperty' ),
new TandemFragmentRenamed( 'numberOfH3OMoleculesProperty', 'particleCountH3OProperty' ),
new TandemFragmentRenamed( 'numberOfOHMoleculesProperty', 'particleCountOHProperty' ),
new TandemFragmentRenamed( 'beakerControlPanel.moleculeCountCheckbox', 'beakerControlPanel.particleCountsCheckbox' ),
new TandemFragmentRenamed( 'viewProperties.moleculeCountVisibleProperty', 'viewProperties.particleCountsVisibleProperty' ),
new TandemFragmentRenamed( 'view.moleculeCountNode', 'view.particleCountsNode' )
```

**Comment by pixelzoom** [comment]
Back to @Nancy-Salpepi and @arouinfar to test-drive in master.  The checkbox is now labeled "Particle Counts", and where you previous saw "molecule" in the Studio tree, you will now see "particle".

**Comment by Nancy-Salpepi** [comment]
Thanks for making the change. Things look good to me on master. 
Migration is working as expected. I see all the "Molecule Count" to "Particle Count" changes listed in the console in studio 1.6.0-dev.1. 
<img width="748" alt="Screenshot 2022-12-19 at 9 22 19 AM" src="https://user-images.githubusercontent.com/87318828/208452276-ce75b9d0-8b54-4e9e-bdfa-8aebc56ef6f3.png">

<img width="748" alt="Screenshot 2022-12-19 at 9 23 16 AM" src="https://user-images.githubusercontent.com/87318828/208452296-dfcccd77-bd5b-48b5-bce3-e799270003a9.png">

The basics version doesn't have "Molecule" in the tree(at least that I saw). A test migration worked as expected.

**Comment by pixelzoom** [comment]
Excellent, thanks @Nancy-Salpepi.

@arouinfar if everything looks OK after your reviw, feel free to close.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi @pixelzoom! Everything looks good in master, closing.
