### ISSUE TITLE
dragListener isn't interrupted when moving 2nd Indicator with multitouch

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ph-scale#261]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 16.1.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/866,  on the My Solution Screen, if I hold `indicatorH3ONode` with one finger and then attempt to move `indicatorOHNode` with another, their positions will flip back and forth. The finger I lift second determines the final position of the indicators. 
This also happens if I hold the hydroxide node first and then attempt to move the hydronium ion. Also seen in published. 

**Steps to reproduce**
1. On the iPad, go to the My Solutions Screen
2. With one finger hold the H3O+ Indicator 
3. With a second finger, move the OH- Indicator

**Visuals**

https://user-images.githubusercontent.com/87318828/208504888-5100ebfc-fd8f-480a-b723-328b38ad5a7a.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.6.0-dev.6/phet/ph-scale_all_phet.html
Version: 1.6.0-dev.6 2022-12-15 16:50:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1463x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Excellent observation @Nancy-Salpepi.

I vaguely recall discussing this long long ago, and deciding that, because it didn't break anything, this was in the category of "well don't do that then", and we would therefore do nothing.  Or maybe I dreamt it...  In any case, making drag mututally-exclusive here is the right thing to do, and it's relatively easy.  So I've made it so.  

@Nancy-Salpepi please verify in master or [1.6.0-dev.7](https://phet-dev.colorado.edu/html/ph-scale/1.6.0-dev.7/phet/ph-scale_en_phet.html).  If all looks well, please close.

**Comment by Nancy-Salpepi** [comment]
It is working very nicely in master @pixelzoom! Closing.
