### ISSUE TITLE
change 'Custom' screen name?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#46]
See https://github.com/phetsims/acid-base-solutions/issues/122

The 'Custom Solutions' screen in Acid-Base Solutions was renamed 'My Solution'.  pH Scale has a similar screen, currently named 'Custom'.  Is any change required for pH Scale?

**Comment by pixelzoom** [comment]
@ycarpenterphet We'll be redeploying this sim sometime soon, specially for translations. If you want to make this change, now would be the time, before it gets translated. Your decision?...

**Comment by ycarpenterphet** [comment]
Let's go ahead and rename the screen 'My Solution.' 

It will make things a bit more consistent across sims, and have the bonus that it is less ambiguous in the series of screen names (with Custom following on the heels of 'Macro' and 'Micro', it could easily imply to teachers that you're customizing the scale at which you're observing, rather than the solution itself, even though this isn't the case with students).

Aside: I am about to record a teacher primer video to give new teachers a quick walkthrough of the sim features.  @pixelzoom: When might it be possible to have a dev version available with this new screen title available, so that I can make sure that the screencapture video matches the soon to be redeployed sim?

Also, when is the updated sim likely to be redeployed/published to the website? That will be useful info for the primer team to make a judgement call on when to post the video. Thanks!

**Comment by pixelzoom** [comment]
@ycarpenterphet:

Screen has been renamed "My Solution".  GitHub directory structure and JavaScript file names have been modified accordingly. 

Here's the dev version requested:
http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.0-dev.1/ph-scale_en.html

I have no idea when this sim is likely to be redeployed. I suggest that you communicate with @ariel-phet if there are scheduling dependencies.

If the dev version looks OK, please close this issue.

**Comment by ycarpenterphet** [comment]
Dev version looks great, thanks! I'll touch base with @ariel-phet about the deployment.

Closing this issue.
