### ISSUE TITLE
Checking "H3O+/OH- Ratio" checkbox takes ~1 second

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/ph-scale#82]
**Test Device**

Hopper, Leibniz

**Operating System**

iOS 12.3.1

**Browser**

Mobile Safari 12

**Problem Description**

For https://github.com/phetsims/QA/issues/323. In the "Micro" and "My Solutions" screens, if you have lots of ions of either kind, i.e. the solution is either highly acidic or highly basic, and you check the hydronium / hydroxide ratio checkbox, it takes about one second for the ions to appear.

**Visuals**

It doesn't look that bad in this gif, but it is noticeable when you're playing with the sim.

![issue](https://user-images.githubusercontent.com/31285590/58594601-4dae8b80-822b-11e9-9c0b-38ce32621526.gif)

**Comment by pixelzoom** [comment]
Thanks for reporting.

The time it takes to display the image depends on the number of molecules; more molecules requires more time.  And the implementation is unchanged from the published version.  That said...

I tested on both ends of the iPad spectrum (iPad6 + iOS12, iPad2 + iOS9) and performance seems acceptable. @arouinfar please confirm. If it's not acceptable, I'll investigate whether there's a more efficient way to draw the molecules.

**Comment by arouinfar** [comment]
@lmulhall-phet observed this issue on some of our newest iPads, Hopper (iPad 6, iOS 12) and Leibniz (iPad Air 2, iOS 12). Testing myself, I would say that the lag is borderline acceptable. The lag is long enough that some users may end up tapping the checkbox a 2nd time while waiting for the particles to appear, thereby unchecking the checkbox. While annoying, this issue isn't particularly harmful. 

Interestingly, latest (1.2.18) is buttery smooth, and there is absolutely no noticeable lag. Perhaps the 1.3 branch has picked up some common code changes which significantly slow things down. I think a short investigation might be worthwhile @pixelzoom.

**Comment by pixelzoom** [comment]
> ... Interestingly, latest (1.2.18) is buttery smooth ...

Rendering is performed in `RatioNode`.   Looking through changes since the 1.2 release branch was created on 11/17/2015...    The most likely suspect is https://github.com/phetsims/ph-scale/commit/8b1ee98ac174a74521937741bae80ccaa5bf8068, where `toImage` was replaced by `toCanvas` for  phetsims/scenery#250.

**Comment by pixelzoom** [comment]
Rendering of H<sub>3</sub>O<sup>+</sup>/OH<sup>-</sup> Ratio is performed in `RatioNode`.   
This issue and https://github.com/phetsims/ph-scale/issues/83 are identical, because `RatioNode` is not updated until it becomes visible.  So checking the checkbox is equivalent to selecting a new solute.   So I'm going to close this issue as "duplicate", and continue work in https://github.com/phetsims/ph-scale/issues/83.
